# Generated by Django 5.1.7 on 2025-03-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_map_is_current_map_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
