# Generated by Django 5.1.7 on 2025-03-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='language',
            field=models.CharField(default='en', max_length=50),
        ),
    ]
