# Generated by Django 5.1.7 on 2025-03-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_robot_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=2),
        ),
    ]
