# Generated by Django 5.1.7 on 2025-03-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_alter_robot_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='column',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='robot',
            name='direction',
            field=models.CharField(choices=[('up', 'Up'), ('right', 'Right'), ('down', 'Down'), ('left', 'Left')], default='up', max_length=5),
        ),
        migrations.AddField(
            model_name='robot',
            name='floor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='robot',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='robot',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='robot',
            name='row',
            field=models.IntegerField(default=0),
        ),
    ]
