# Generated by Django 5.1.7 on 2025-03-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='map',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
