# Generated by Django 5.1.7 on 2025-03-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_map_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='matrix',
        ),
        migrations.AddField(
            model_name='map',
            name='cols',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='map',
            name='matrices',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='map',
            name='rows',
            field=models.IntegerField(default=4),
        ),
    ]
