# Generated by Django 5.1.7 on 2025-03-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_remove_map_matrix_map_cols_map_matrices_map_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='rooms',
            field=models.JSONField(default=list),
        ),
    ]
